# standard library imports
#
import os

# third party imports
#
from snakemake.utils import report

# project specific imports
# /


LIB_PATH = os.path.abspath(
    os.path.join(os.path.dirname(os.path.realpath(workflow.snakefile)), "..", "..", "lib"))
if LIB_PATH not in sys.path:
    sys.path.insert(0, LIB_PATH)

    
RESULT_OUTDIR = './out'


# non-login bash
shell.executable("/bin/bash")
shell.prefix("source rc/snakemake_env.rc;")


include: "../../rules/logging.rules"
include: "../../rules/samtools.rules"
include: "../../rules/sambamba.rules"
include: "../../rules/report.rules"
include: "bwa_mem.rules"

                    
localrules: final, report


out_template = os.path.join(RESULT_OUTDIR, '{sample}/{sample}.bwamem')
if config['mark_dups']:
    out_template += ".dedup"

rule final:
    input:
        bams = expand(out_template + ".bam.bai", sample=config['samples']),
        bamstats = expand(out_template + ".bamstats/stats_plot.html", sample=config['samples']),
        report = "report.html"
    message:
        """
        Pipeline run successfully completed
        """
    # Set no output in final rule. Otherwise deletion of any input will not result in a rerun

        
