# standard library imports
#
#/

# third party imports
#
from snakemake.utils import report

# project specific imports
#
LIB_PATH = os.path.abspath(
    os.path.join(os.path.dirname(os.path.realpath(workflow.snakefile)), "..", "..", "lib"))
if LIB_PATH not in sys.path:
    sys.path.insert(0, LIB_PATH)

    
RESULT_OUTDIR = 'out'


# non-login bash
shell.executable("/bin/bash")
shell.prefix("source rc/snakemake_env.rc;")

include: "../../rules/logging.rules"
include: "../../rules/report.rules"
include: "../../rules/vcf.rules"
include: "gatk_haplotype_caller.rules"

localrules: final, gatk_catvariants, tabix

rule final:
    input:
        expand(os.path.join(
            RESULT_OUTDIR, "{sample}.concat.g.vcf.gz.tbi"),
            sample=config['sample_bam_map'])

