# non-login bash
shell.executable("/bin/bash")
shell.prefix("source snakemake_env.rc;")

include:
    "../rules/samtools.rules"
include:
    "gatk_mapping.rules"
include:
    "gatk_variant_recalibrator.rules"
include:
    "gatk_haplotype_caller.rules"

rule all:
    input:
        "variant_calling/all_genotyped.snp_recal.indel_recal.vcf"
